# june23_gpt_telegram

just added gpt-3.5-turbo in gpt.py

couldn't test anything though because of 
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

had like 3 api keys already :/
